### ISSUE TITLE
how to pre training the model from scratch, 

### ISSUE THREAD

**Issue by SeekPoint** [jcyk/BERT#2]
for example, if we use sample_from_zhwiki as corpus

**Comment by jcyk** [comment]
first use `preprocess.py` then `train.sh` (`train.py`)
detailed configurations can be found in the code.

**Comment by SeekPoint** [comment]
looks the toy\train and toy\vocab are not generated by prprocess.py

have you ever run a pre-training process form scratch?

**Comment by jcyk** [comment]
1. `python preprocess.py`
2. `sh train.sh`

For hyper-parameter and all other settings, see the argument parsers in the above two files. We provide a piece of raw text from zhwiki in `toy` folder.
